# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - tenv # Replaced by usetesting
    # Identiying raised
    - wsl
    - wrapcheck
    - varnamelen
    - usestdlibvars
    - testpackage
    - perfsprint
    - paralleltest
    - nlreturn
    - lll
    - gosimple
    - ireturn
    - gofumpt
    - goimports
    - godox
    - gci
    - gochecknoglobals
    - funlen
    - exhaustruct
    - depguard
    - cyclop
    - revive
    - gosec
    - stylecheck
    - err113
    - dupl
