package provider

import (
	"context"
	"fmt"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &notificationPublisherResource{}
	_ resource.ResourceWithConfigure   = &notificationPublisherResource{}
	_ resource.ResourceWithImportState = &notificationPublisherResource{}
)

type (
	notificationPublisherResource struct {
		client *dtrack.Client
		semver *Semver
	}

	notificationPublisherResourceModel struct {
		ID               types.String `tfsdk:"id"`
		Name             types.String `tfsdk:"name"`
		Description      types.String `tfsdk:"description"`
		PublisherClass   types.String `tfsdk:"publisher_class"`
		Template         types.String `tfsdk:"template"`
		TemplateMimeType types.String `tfsdk:"template_mime_type"`
		DefaultPublisher types.Bool   `tfsdk:"default_publisher"`
	}
)

func NewNotificationPublisherResource() resource.Resource {
	return &notificationPublisherResource{}
}

func (*notificationPublisherResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_publisher"
}

func (*notificationPublisherResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Notification Publisher.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "UUID for the Notification Publisher as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the Notification Publisher.",
				Required:    true,
			},
			"description": schema.StringAttribute{
				Description: "Publisher Description.",
				Optional:    true,
				Computed:    true,
			},
			"publisher_class": schema.StringAttribute{
				Description: "Name of Java Class that provides Publisher.",
				Required:    true,
			},
			"template": schema.StringAttribute{
				Description: "Template string value for Publisher Payload.",
				Optional:    true,
				Computed:    true,
			},
			"template_mime_type": schema.StringAttribute{
				Description: "MIME type set when sending a notification, for template.",
				Required:    true,
			},
			"default_publisher": schema.BoolAttribute{
				Description: "Whether this is a default publisher.",
				Computed:    true,
			},
		},
	}
}

func (r *notificationPublisherResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan notificationPublisherResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisherReq := dtrack.NotificationPublisher{
		Name:             plan.Name.ValueString(),
		Description:      plan.Description.ValueString(),
		PublisherClass:   plan.PublisherClass.ValueString(),
		Template:         plan.Template.ValueString(),
		TemplateMIMEType: plan.TemplateMimeType.ValueString(),
	}

	tflog.Debug(ctx, "Creating Notification Publisher", map[string]any{
		"name":               publisherReq.Name,
		"description":        publisherReq.Description,
		"publisher_class":    publisherReq.PublisherClass,
		"template":           publisherReq.Template,
		"template_mime_type": publisherReq.TemplateMIMEType,
	})

	publisherRes, err := r.client.Notification.CreatePublisher(ctx, publisherReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Notification Publisher",
			"Error in publisher: "+publisherReq.Name+", from original error: "+err.Error(),
		)
		return
	}

	newState := notificationPublisherResourceModel{
		ID:               types.StringValue(publisherRes.UUID.String()),
		Name:             types.StringValue(publisherRes.Name),
		Description:      types.StringValue(publisherRes.Description),
		PublisherClass:   types.StringValue(publisherRes.PublisherClass),
		Template:         types.StringValue(publisherRes.Template),
		TemplateMimeType: types.StringValue(publisherRes.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisherRes.DefaultPublisher),
	}

	diags = resp.State.Set(ctx, newState)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Created Notification Publisher", map[string]any{
		"id":                 newState.ID.ValueString(),
		"name":               newState.Name.ValueString(),
		"description":        newState.Description.ValueString(),
		"publisher_class":    newState.PublisherClass.ValueString(),
		"template":           newState.Template.ValueString(),
		"template_mime_type": newState.TemplateMimeType.ValueString(),
		"default_publisher":  newState.DefaultPublisher.ValueBool(),
	})
}

func (r *notificationPublisherResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Fetch state.
	var state notificationPublisherResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Refresh.
	id, diag := TryParseUUID(state.ID, LifecycleRead, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	tflog.Debug(ctx, "Reading Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})

	publishers, err := r.client.Notification.GetAllPublishers(ctx)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to read Notification Publishers",
			"Error when reading ID: "+id.String()+", in original error: "+err.Error(),
		)
		return
	}
	publisher, err := Find(publishers, func(pub dtrack.NotificationPublisher) bool {
		return pub.UUID.String() == id.String()
	})
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to read Notification Publisher",
			"Error with locating ID: "+id.String()+", in original error: "+err.Error(),
		)
		return
	}

	state = notificationPublisherResourceModel{
		ID:               types.StringValue(publisher.UUID.String()),
		Name:             types.StringValue(publisher.Name),
		Description:      types.StringValue(publisher.Description),
		PublisherClass:   types.StringValue(publisher.PublisherClass),
		Template:         types.StringValue(publisher.Template),
		TemplateMimeType: types.StringValue(publisher.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisher.DefaultPublisher),
	}

	// Update state.
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Read Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
}

func (r *notificationPublisherResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get State.
	var plan notificationPublisherResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(plan.ID, LifecycleUpdate, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	publisherReq := dtrack.NotificationPublisher{
		UUID:             id,
		Name:             plan.Name.ValueString(),
		Description:      plan.Description.ValueString(),
		PublisherClass:   plan.PublisherClass.ValueString(),
		Template:         plan.Template.ValueString(),
		TemplateMIMEType: plan.TemplateMimeType.ValueString(),
		DefaultPublisher: plan.DefaultPublisher.ValueBool(),
	}
	// Execute.
	tflog.Debug(ctx, "Updating Notification Publisher", map[string]any{
		"id":                 publisherReq.UUID.String(),
		"name":               publisherReq.Name,
		"description":        publisherReq.Description,
		"publisher_class":    publisherReq.PublisherClass,
		"template":           publisherReq.Template,
		"template_mime_type": publisherReq.TemplateMIMEType,
		"default_publisher":  publisherReq.DefaultPublisher,
	})
	publisherRes, err := r.client.Notification.UpdatePublisher(ctx, publisherReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to update Notification Publisher",
			"Error in: "+id.String()+", from: "+err.Error(),
		)
		return
	}

	// Map SDK to TF.
	state := notificationPublisherResourceModel{
		ID:               types.StringValue(publisherRes.UUID.String()),
		Name:             types.StringValue(publisherRes.Name),
		Description:      types.StringValue(publisherRes.Description),
		PublisherClass:   types.StringValue(publisherRes.PublisherClass),
		Template:         types.StringValue(publisherRes.Template),
		TemplateMimeType: types.StringValue(publisherRes.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisherRes.DefaultPublisher),
	}

	// Update State.
	diags = resp.State.Set(ctx, state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Updated Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
}

func (r *notificationPublisherResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Load state.
	var state notificationPublisherResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(state.ID, LifecycleDelete, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	// Execute.
	tflog.Debug(ctx, "Deleting Notification Publisher", map[string]any{
		"id":                 id.String(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
	err := r.client.Notification.DeletePublisher(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to delete Notification Publisher",
			"Unexpected error when trying to delete Notification Publisher: "+id.String()+", from error: "+err.Error(),
		)
		return
	}
	tflog.Debug(ctx, "Deleted Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
}

func (*notificationPublisherResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Importing Notification Publisher", map[string]any{
		"id": req.ID,
	})
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Imported Notification Publisher", map[string]any{
		"id": req.ID,
	})
}

func (r *notificationPublisherResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfoData, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfoData.client
	r.semver = clientInfoData.semver
}
