package provider

import (
	"context"
	"fmt"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &notificationPublisherResource{}
	_ resource.ResourceWithConfigure   = &notificationPublisherResource{}
	_ resource.ResourceWithImportState = &notificationPublisherResource{}
)

type (
	notificationPublisherResource struct {
		client *dtrack.Client
		semver *Semver
	}

	notificationPublisherResourceModel struct {
		ID               types.String `tfsdk:"id"`
		Name             types.String `tfsdk:"name"`
		Description      types.String `tfsdk:"description"`
		PublisherClass   types.String `tfsdk:"publisher_class"` // API v4.
		ExtensionName    types.String `tfsdk:"extension_name"`  // API v5+.
		Template         types.String `tfsdk:"template"`
		TemplateMimeType types.String `tfsdk:"template_mime_type"`
		DefaultPublisher types.Bool   `tfsdk:"default_publisher"`
	}
)

func NewNotificationPublisherResource() resource.Resource {
	return &notificationPublisherResource{}
}

func (*notificationPublisherResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_publisher"
}

func (*notificationPublisherResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Notification Publisher.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "UUID for the Notification Publisher as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the Notification Publisher.",
				Required:    true,
			},
			"description": schema.StringAttribute{
				Description: "Publisher Description.",
				Optional:    true,
				Computed:    true,
			},
			"publisher_class": schema.StringAttribute{
				Description: "Name of Java Class that provides Publisher. Required for API v4.",
				Optional:    true, // Required in v4. Not valid in v5. Checked in `Create`.
				Computed:    true,
			},
			"extension_name": schema.StringAttribute{
				Description: "Name of extension that provides Publisher. Required for API v5+.",
				Optional:    true, // Required in v5. Not valid in v4. Checked in `Create`.
				Computed:    true,
			},
			"template": schema.StringAttribute{
				Description: "Template string value for Publisher Payload.",
				Optional:    true,
				Computed:    true,
			},
			"template_mime_type": schema.StringAttribute{
				Description: "MIME type set when sending a notification, for template.",
				Required:    true,
			},
			"default_publisher": schema.BoolAttribute{
				Description: "Whether this is a default publisher.",
				Computed:    true,
			},
		},
	}
}

func (r *notificationPublisherResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan notificationPublisherResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisherReq := dtrack.NotificationPublisher{
		Name:             plan.Name.ValueString(),
		Description:      plan.Description.ValueString(),
		PublisherClass:   plan.PublisherClass.ValueString(),
		ExtensionName:    plan.ExtensionName.ValueString(),
		Template:         plan.Template.ValueString(),
		TemplateMIMEType: plan.TemplateMimeType.ValueString(),
	}

	if r.semver.Major == 4 && (plan.PublisherClass.IsNull() || plan.PublisherClass.IsUnknown()) {
		resp.Diagnostics.AddAttributeError(
			path.Root("publisher_class"),
			"Missing required attribute",
			"publisher_class attribute is required for API v4, but was not provided",
		)
	}
	if r.semver.Major == 5 && (plan.ExtensionName.IsNull() || plan.ExtensionName.IsUnknown()) {
		resp.Diagnostics.AddAttributeError(
			path.Root("extension_name"),
			"Missing required attribute",
			"extension_name attribute is required for API v5, but was not provided",
		)
	}
	if r.semver.Major == 4 && !(plan.ExtensionName.IsNull() || plan.ExtensionName.IsUnknown()) {
		resp.Diagnostics.AddAttributeWarning(
			path.Root("extension_name"),
			"Provided unused attribute",
			"extension-name attribute is unused for API v4, but was provided",
		)
	}
	if r.semver.Major == 5 && !(plan.PublisherClass.IsNull() || plan.PublisherClass.IsUnknown()) {
		resp.Diagnostics.AddAttributeWarning(
			path.Root("publisher_class"),
			"Provided unused attribute",
			"publisher_class attribute is unused for API v5, but was provided",
		)
	}
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Creating Notification Publisher", map[string]any{
		"name":               publisherReq.Name,
		"description":        publisherReq.Description,
		"publisher_class":    publisherReq.PublisherClass,
		"extension_name":     publisherReq.ExtensionName,
		"template":           publisherReq.Template,
		"template_mime_type": publisherReq.TemplateMIMEType,
	})

	publisherRes, err := r.client.Notification.CreatePublisher(ctx, publisherReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Notification Publisher",
			"Error in publisher: "+publisherReq.Name+", from original error: "+err.Error(),
		)
		return
	}

	newState := notificationPublisherResourceModel{
		ID:               types.StringValue(publisherRes.UUID.String()),
		Name:             types.StringValue(publisherRes.Name),
		Description:      types.StringValue(publisherRes.Description),
		PublisherClass:   types.StringValue(publisherRes.PublisherClass),
		ExtensionName:    types.StringValue(publisherRes.ExtensionName),
		Template:         types.StringValue(publisherRes.Template),
		TemplateMimeType: types.StringValue(publisherRes.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisherRes.DefaultPublisher),
	}

	diags = resp.State.Set(ctx, newState)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Created Notification Publisher", map[string]any{
		"id":                 newState.ID.ValueString(),
		"name":               newState.Name.ValueString(),
		"description":        newState.Description.ValueString(),
		"publisher_class":    newState.PublisherClass.ValueString(),
		"extension_name":     newState.ExtensionName.ValueString(),
		"template":           newState.Template.ValueString(),
		"template_mime_type": newState.TemplateMimeType.ValueString(),
		"default_publisher":  newState.DefaultPublisher.ValueBool(),
	})
}

func (r *notificationPublisherResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Fetch state.
	var state notificationPublisherResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Refresh.
	id, diag := TryParseUUID(state.ID, LifecycleRead, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	tflog.Debug(ctx, "Reading Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"extension_name":     state.ExtensionName.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})

	publishers, err := r.client.Notification.GetAllPublishers(ctx)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to read Notification Publishers",
			"Error when reading ID: "+id.String()+", in original error: "+err.Error(),
		)
		return
	}
	publisher, err := Find(publishers, func(pub dtrack.NotificationPublisher) bool {
		return pub.UUID.String() == id.String()
	})
	if err != nil {
		err := err.Error()
		if err == "did not find item" {
			tflog.Warn(ctx, "Unable to read missing Notification Publisher. Will be removed from state.", map[string]any{
				"id":    state.ID.ValueString(),
				"name":  state.Name.ValueString(),
				"class": state.PublisherClass.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Unable to read Notification Publisher",
			"Error with locating ID: "+id.String()+", in original error: "+err,
		)
		return
	}

	state = notificationPublisherResourceModel{
		ID:               types.StringValue(publisher.UUID.String()),
		Name:             types.StringValue(publisher.Name),
		Description:      types.StringValue(publisher.Description),
		PublisherClass:   types.StringValue(publisher.PublisherClass),
		ExtensionName:    types.StringValue(publisher.ExtensionName),
		Template:         types.StringValue(publisher.Template),
		TemplateMimeType: types.StringValue(publisher.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisher.DefaultPublisher),
	}

	// Update state.
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Read Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"extension_name":     state.ExtensionName.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
}

func (r *notificationPublisherResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get State.
	var plan notificationPublisherResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(plan.ID, LifecycleUpdate, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	publisherReq := dtrack.NotificationPublisher{
		UUID:             id,
		Name:             plan.Name.ValueString(),
		Description:      plan.Description.ValueString(),
		PublisherClass:   plan.PublisherClass.ValueString(),
		ExtensionName:    plan.ExtensionName.ValueString(),
		Template:         plan.Template.ValueString(),
		TemplateMIMEType: plan.TemplateMimeType.ValueString(),
		DefaultPublisher: plan.DefaultPublisher.ValueBool(),
	}
	// Execute.
	tflog.Debug(ctx, "Updating Notification Publisher", map[string]any{
		"id":                 publisherReq.UUID.String(),
		"name":               publisherReq.Name,
		"description":        publisherReq.Description,
		"publisher_class":    publisherReq.PublisherClass,
		"extension_name":     publisherReq.ExtensionName,
		"template":           publisherReq.Template,
		"template_mime_type": publisherReq.TemplateMIMEType,
		"default_publisher":  publisherReq.DefaultPublisher,
	})
	publisherRes, err := r.client.Notification.UpdatePublisher(ctx, publisherReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to update Notification Publisher",
			"Error in: "+id.String()+", from: "+err.Error(),
		)
		return
	}

	// Map SDK to TF.
	state := notificationPublisherResourceModel{
		ID:               types.StringValue(publisherRes.UUID.String()),
		Name:             types.StringValue(publisherRes.Name),
		Description:      types.StringValue(publisherRes.Description),
		PublisherClass:   types.StringValue(publisherRes.PublisherClass),
		ExtensionName:    types.StringValue(publisherRes.ExtensionName),
		Template:         types.StringValue(publisherRes.Template),
		TemplateMimeType: types.StringValue(publisherRes.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisherRes.DefaultPublisher),
	}

	// Update State.
	diags = resp.State.Set(ctx, state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Updated Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"extension_name":     state.ExtensionName.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
}

func (r *notificationPublisherResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Load state.
	var state notificationPublisherResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(state.ID, LifecycleDelete, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	// Execute.
	tflog.Debug(ctx, "Deleting Notification Publisher", map[string]any{
		"id":                 id.String(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"extension_name":     state.ExtensionName.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
	err := r.client.Notification.DeletePublisher(ctx, id)
	if err != nil {
		err := err.Error()
		// Mismatch of `rule` rather than `publisher` is caused by bug in API returning the incorrect response.
		if err == "The UUID of the notification rule could not be found. (status: 404)" {
			tflog.Warn(ctx, "Unable to delete missing Notification Publisher. Ignoring since is desired state.", map[string]any{
				"id":   state.ID.ValueString(),
				"name": state.Name.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError(
			"Unable to delete Notification Publisher",
			"Unexpected error when trying to delete Notification Publisher: "+id.String()+", from error: "+err,
		)
		return
	}
	tflog.Debug(ctx, "Deleted Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"extension_name":     state.ExtensionName.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
}

func (*notificationPublisherResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Importing Notification Publisher", map[string]any{
		"id": req.ID,
	})
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Imported Notification Publisher", map[string]any{
		"id": req.ID,
	})
}

func (r *notificationPublisherResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfoData, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfoData.client
	r.semver = clientInfoData.semver
}
