package provider

import (
	"context"
	"fmt"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &notificationRuleResource{}
	_ resource.ResourceWithConfigure   = &notificationRuleResource{}
	_ resource.ResourceWithImportState = &notificationRuleResource{}
)

type (
	notificationRuleResource struct {
		client *dtrack.Client
		semver *Semver
	}

	notificationRuleResourceModel struct {
		ID                    types.String `tfsdk:"id"`
		Name                  types.String `tfsdk:"name"`
		Enabled               types.Bool   `tfsdk:"enabled"`
		NotifyChildren        types.Bool   `tfsdk:"notify_children"`
		LogSuccessfulPublish  types.Bool   `tfsdk:"log_successful_publish"`
		Scope                 types.String `tfsdk:"scope"`
		NotificationLevel     types.String `tfsdk:"notification_level"`
		NotifyOn              types.List   `tfsdk:"notify_on"`
		TriggerType           types.String `tfsdk:"trigger_type"`
		Message               types.String `tfsdk:"message"`
		ScheduleCron          types.String `tfsdk:"schedule_cron"`
		ScheduleSkipUnchanged types.Bool   `tfsdk:"schedule_skip_unchanged"`
		PublisherConfig       types.String `tfsdk:"publisher_config"`
		PublisherID           types.String `tfsdk:"publisher_id"`
	}
)

func NewNotificationRuleResource() resource.Resource {
	return &notificationRuleResource{}
}

func (*notificationRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_rule"
}

func (*notificationRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Notification Rule.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "UUID for the Notification Rule as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the Notification Rule.",
				Required:    true,
			},
			"enabled": schema.BoolAttribute{
				Description: "Whether the rule is enabled.",
				Default:     booldefault.StaticBool(true),
				Optional:    true,
				Computed:    true,
			},
			"notify_children": schema.BoolAttribute{
				Description: "Whether to notify children in child projects. Available in API 4.12+.",
				Default:     booldefault.StaticBool(true),
				Optional:    true,
				Computed:    true,
			},
			"log_successful_publish": schema.BoolAttribute{
				Description: "Whethe to log each time a rule is successfully notified.",
				Default:     booldefault.StaticBool(false),
				Optional:    true,
				Computed:    true,
			},
			"scope": schema.StringAttribute{
				Description: "Scope to which this alert applies. See DependencyTrack for valid values.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("PORTFOLIO"),
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"notification_level": schema.StringAttribute{
				Description: "Notification Level to set for Alert. See DependencyTrack for valid values.",
				Optional:    true,
				Computed:    true,
			},
			"notify_on": schema.ListAttribute{
				Description: "Events on which to trigger alert. Only relevant for trigger_type = \"EVENT\".",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
			},
			"trigger_type": schema.StringAttribute{
				Description:   "Type of trigger for Rule. See DependencyTrack for valid values. Only relevant for API 4.13+.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"message": schema.StringAttribute{
				Description: "Alert Rule Message.",
				Optional:    true,
				Computed:    true,
			},
			"schedule_cron": schema.StringAttribute{
				Description: "CRON expression for schedule.",
				Optional:    true,
				Computed:    true,
			},
			"schedule_skip_unchanged": schema.BoolAttribute{
				Description: "Skip sending alert if there is no change.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
			"publisher_config": schema.StringAttribute{
				Description: "Additional configuration to pass to the publisher. Format is custom per publisher.",
				Optional:    true,
				Computed:    true,
			},
			"publisher_id": schema.StringAttribute{
				Description:   "UUID of the Publisher to use for this alert rule.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
		},
	}
}

func (r *notificationRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan notificationRuleResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	notifyOn, err := GetStringList(ctx, &resp.Diagnostics, plan.NotifyOn)
	if err != nil {
		resp.Diagnostics.AddAttributeError(
			path.Root("notify_on"),
			"Unable to Create Notification Rule",
			"Error with notify_on, in original error: "+err.Error(),
		)
	}
	publisherID, diag := TryParseUUID(plan.PublisherID, LifecycleCreate, path.Root("publisher_id"))
	resp.Diagnostics.Append(diag)
	if resp.Diagnostics.HasError() {
		return
	}

	ruleReq := dtrack.NotificationRule{
		Name:                  plan.Name.ValueString(),
		Enabled:               plan.Enabled.ValueBool(),
		LogSuccessfulPublish:  plan.LogSuccessfulPublish.ValueBool(),
		Scope:                 dtrack.NotificationRuleScope(plan.Scope.ValueString()),
		NotificationLevel:     dtrack.NotificationRuleLevel(plan.NotificationLevel.ValueString()),
		NotifyOn:              Map(notifyOn, func(on string) dtrack.NotificationRuleNotifyOn { return dtrack.NotificationRuleNotifyOn(on) }),
		TriggerType:           dtrack.NotificationRuleTriggerType(plan.TriggerType.ValueString()),
		Message:               plan.Message.ValueString(),
		ScheduleCron:          plan.ScheduleCron.ValueString(),
		ScheduleSkipUnchanged: plan.ScheduleSkipUnchanged.ValueBool(),
		PublisherConfig:       plan.PublisherConfig.ValueString(),
		Publisher: dtrack.NotificationPublisher{
			UUID: publisherID,
		},
	}
	if r.semver.Major == 4 && r.semver.Minor >= 12 {
		ruleReq.NotifyChildren = plan.NotifyChildren.ValueBool()
	}

	tflog.Debug(ctx, "Creating Notification Rule", map[string]any{
		"name":                    ruleReq.Name,
		"enabled":                 ruleReq.Enabled,
		"notify_children":         ruleReq.NotifyChildren,
		"log_successful_publish":  ruleReq.LogSuccessfulPublish,
		"scope":                   ruleReq.Scope,
		"notification_level":      ruleReq.NotificationLevel,
		"notify_on":               ruleReq.NotifyOn,
		"trigger_type":            ruleReq.TriggerType,
		"message":                 ruleReq.Message,
		"schedule_cron":           ruleReq.ScheduleCron,
		"schedule_skip_unchanged": ruleReq.ScheduleSkipUnchanged,
		"publisher_config":        ruleReq.PublisherConfig,
		"publisher_id":            ruleReq.Publisher.UUID.String(),
	})

	ruleRes, err := r.client.Notification.CreateRule(ctx, ruleReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating Notification Rule",
			"Error in rule: "+ruleReq.Name+", from original error: "+err.Error(),
		)
		return
	}

	newNotifyOn, diags := types.ListValue(types.StringType, Map(ruleRes.NotifyOn, func(on dtrack.NotificationRuleNotifyOn) attr.Value {
		return types.StringValue(string(on))
	}))
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	newState := notificationRuleResourceModel{
		ID:                    types.StringValue(ruleRes.UUID.String()),
		Name:                  types.StringValue(ruleRes.Name),
		Enabled:               types.BoolValue(ruleRes.Enabled),
		NotifyChildren:        types.BoolUnknown(), // Set Below - 4.12+.
		LogSuccessfulPublish:  types.BoolValue(ruleRes.LogSuccessfulPublish),
		Scope:                 types.StringValue(string(ruleRes.Scope)),
		NotificationLevel:     types.StringValue(string(ruleRes.NotificationLevel)),
		NotifyOn:              newNotifyOn,
		TriggerType:           types.StringValue(string(ruleRes.TriggerType)),
		Message:               types.StringValue(ruleRes.Message),
		ScheduleCron:          types.StringValue(ruleRes.ScheduleCron),
		ScheduleSkipUnchanged: types.BoolValue(ruleRes.ScheduleSkipUnchanged),
		PublisherConfig:       types.StringValue(ruleRes.PublisherConfig),
		PublisherID:           types.StringValue(ruleRes.Publisher.UUID.String()),
	}
	if r.semver.Major == 4 && r.semver.Minor >= 12 {
		newState.NotifyChildren = types.BoolValue(ruleRes.NotifyChildren)
	}

	diags = resp.State.Set(ctx, newState)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Created Notification Rule", map[string]any{
		"id":                      newState.ID,
		"name":                    newState.Name,
		"enabled":                 newState.Enabled,
		"notify_children":         newState.NotifyChildren,
		"log_successful_publish":  newState.LogSuccessfulPublish,
		"scope":                   newState.Scope,
		"notification_level":      newState.NotificationLevel,
		"notify_on":               newState.NotifyOn,
		"trigger_type":            newState.TriggerType,
		"message":                 newState.Message,
		"schedule_cron":           newState.ScheduleCron,
		"schedule_skip_unchanged": newState.ScheduleSkipUnchanged,
		"publisher_config":        newState.PublisherConfig,
		"publisher_id":            newState.PublisherID,
	})
}

func (r *notificationRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Fetch state.
	var state notificationRuleResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Refresh.
	/*id, diag := TryParseUUID(state.ID, LifecycleRead, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	tflog.Debug(ctx, "Reading Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})

	publishers, err := r.client.Notification.GetAllPublishers(ctx)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to read Notification Publishers",
			"Error when reading ID: "+id.String()+", in original error: "+err.Error(),
		)
		return
	}
	publisher, err := Find(publishers, func(pub dtrack.NotificationPublisher) bool {
		return pub.UUID.String() == id.String()
	})
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to read Notification Publisher",
			"Error with locating ID: "+id.String()+", in original error: "+err.Error(),
		)
		return
	}

	state = notificationRuleResourceModel{
		ID:               types.StringValue(publisher.UUID.String()),
		Name:             types.StringValue(publisher.Name),
		Description:      types.StringValue(publisher.Description),
		PublisherClass:   types.StringValue(publisher.PublisherClass),
		Template:         types.StringValue(publisher.Template),
		TemplateMimeType: types.StringValue(publisher.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisher.DefaultPublisher),
	}

	// Update state.
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Read Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})*/
}

func (r *notificationRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get State.
	var plan notificationRuleResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	/*id, diag := TryParseUUID(plan.ID, LifecycleUpdate, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	publisherReq := dtrack.NotificationPublisher{
		UUID:             id,
		Name:             plan.Name.ValueString(),
		Description:      plan.Description.ValueString(),
		PublisherClass:   plan.PublisherClass.ValueString(),
		Template:         plan.Template.ValueString(),
		TemplateMIMEType: plan.TemplateMimeType.ValueString(),
		DefaultPublisher: plan.DefaultPublisher.ValueBool(),
	}
	// Execute.
	tflog.Debug(ctx, "Updating Notification Publisher", map[string]any{
		"id":                 publisherReq.UUID.String(),
		"name":               publisherReq.Name,
		"description":        publisherReq.Description,
		"publisher_class":    publisherReq.PublisherClass,
		"template":           publisherReq.Template,
		"template_mime_type": publisherReq.TemplateMIMEType,
		"default_publisher":  publisherReq.DefaultPublisher,
	})
	publisherRes, err := r.client.Notification.UpdatePublisher(ctx, publisherReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to update Notification Publisher",
			"Error in: "+id.String()+", from: "+err.Error(),
		)
		return
	}

	// Map SDK to TF.
	state := notificationRuleResourceModel{
		ID:               types.StringValue(publisherRes.UUID.String()),
		Name:             types.StringValue(publisherRes.Name),
		Description:      types.StringValue(publisherRes.Description),
		PublisherClass:   types.StringValue(publisherRes.PublisherClass),
		Template:         types.StringValue(publisherRes.Template),
		TemplateMimeType: types.StringValue(publisherRes.TemplateMIMEType),
		DefaultPublisher: types.BoolValue(publisherRes.DefaultPublisher),
	}

	// Update State.
	diags = resp.State.Set(ctx, state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Updated Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})*/
}

func (r *notificationRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Load state.
	/*var state notificationRuleResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(state.ID, LifecycleDelete, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	// Execute.
	tflog.Debug(ctx, "Deleting Notification Publisher", map[string]any{
		"id":                 id.String(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})
	err := r.client.Notification.DeletePublisher(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to delete Notification Publisher",
			"Unexpected error when trying to delete Notification Publisher: "+id.String()+", from error: "+err.Error(),
		)
		return
	}
	tflog.Debug(ctx, "Deleted Notification Publisher", map[string]any{
		"id":                 state.ID.ValueString(),
		"name":               state.Name.ValueString(),
		"description":        state.Description.ValueString(),
		"publisher_class":    state.PublisherClass.ValueString(),
		"template":           state.Template.ValueString(),
		"template_mime_type": state.TemplateMimeType.ValueString(),
		"default_publisher":  state.DefaultPublisher.ValueBool(),
	})*/
}

func (*notificationRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Importing Notification Rule", map[string]any{
		"id": req.ID,
	})
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Imported Notification Rule", map[string]any{
		"id": req.ID,
	})
}

func (r *notificationRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfoData, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfoData.client
	r.semver = clientInfoData.semver
}
