package provider

import (
	"context"
	"fmt"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &oidcGroupResource{}
	_ resource.ResourceWithConfigure   = &oidcGroupResource{}
	_ resource.ResourceWithImportState = &oidcGroupResource{}
)

func NewOidcGroupResource() resource.Resource {
	return &oidcGroupResource{}
}

type oidcGroupResource struct {
	client *dtrack.Client
	semver *Semver
}

type oidcGroupResourceModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}

func (r *oidcGroupResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_oidc_group"
}

func (r *oidcGroupResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a OIDC Group.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "UUID for the OIDC Group as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the OIDC Group.",
				Required:    true,
			},
		},
	}
}

func (r *oidcGroupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan oidcGroupResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	groupName := plan.Name.ValueString()
	tflog.Debug(ctx, "Creating OIDC Group", map[string]any{
		"name": groupName,
	})
	oidcGroupRes, err := r.client.OIDC.CreateGroup(ctx, groupName)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating oidc group",
			"Could not create oidc group, unexpected error within Client: "+err.Error(),
		)
		return
	}
	plan = oidcGroupResourceModel{
		ID:   types.StringValue(oidcGroupRes.UUID.String()),
		Name: types.StringValue(oidcGroupRes.Name),
	}
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Created OIDC Group", map[string]any{
		"id":   plan.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
}

func (r *oidcGroupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Fetch state.
	var state oidcGroupResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Refresh.
	tflog.Debug(ctx, "Reading OIDC Group", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
	id, diag := TryParseUUID(state.ID, LifecycleRead, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	oidcGroup, err := FindPaged(
		func(po dtrack.PageOptions) (dtrack.Page[dtrack.OIDCGroup], error) {
			return r.client.OIDC.GetAllGroups(ctx, po)
		},
		func(group dtrack.OIDCGroup) bool {
			return group.UUID == id
		},
	)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to get updated oidc group",
			"Error with reading oidc group: "+id.String()+", in original error: "+err.Error(),
		)
		return
	}
	state = oidcGroupResourceModel{
		ID:   types.StringValue(oidcGroup.UUID.String()),
		Name: types.StringValue(oidcGroup.Name),
	}

	// Update state.
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Read OIDC Group", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

func (r *oidcGroupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get State.
	var plan oidcGroupResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(plan.ID, LifecycleUpdate, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	oidcGroupReq := dtrack.OIDCGroup{
		UUID: id,
		Name: plan.Name.ValueString(),
	}

	// Execute.
	tflog.Debug(ctx, "Updating OIDC Group", map[string]any{
		"id":   oidcGroupReq.UUID.String(),
		"name": oidcGroupReq.Name,
	})
	oidcGroupRes, err := r.client.OIDC.UpdateGroup(ctx, oidcGroupReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to update oidc group",
			"Error in: "+id.String()+", from: "+err.Error(),
		)
		return
	}

	// Map SDK to TF.
	plan = oidcGroupResourceModel{
		ID:   types.StringValue(oidcGroupRes.UUID.String()),
		Name: types.StringValue(oidcGroupRes.Name),
	}

	// Update State.
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Updated OIDC Group", map[string]any{
		"id":   plan.ID.ValueString(),
		"name": plan.Name.ValueString(),
	})
}

func (r *oidcGroupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Load state.
	var state oidcGroupResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK.
	id, diag := TryParseUUID(state.ID, LifecycleDelete, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	// Execute.
	tflog.Debug(ctx, "Deleting OIDC Group", map[string]any{
		"id":   id.String(),
		"name": state.Name.ValueString(),
	})
	err := r.client.OIDC.DeleteGroup(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to delete oidc group",
			"Unexpected error when trying to delete oidc group: "+id.String()+", error: "+err.Error(),
		)
		return
	}
	tflog.Debug(ctx, "Deleted OIDC Group", map[string]any{
		"id":   state.ID.ValueString(),
		"name": state.Name.ValueString(),
	})
}

func (r *oidcGroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Debug(ctx, "Importing OIDC Group", map[string]any{
		"id": req.ID,
	})
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Imported OIDC Group", map[string]any{
		"id": req.ID,
	})
}

func (r *oidcGroupResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfoData, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfoData.client
	r.semver = clientInfoData.semver
}
