package provider

import (
	"context"
	"fmt"

	dtrack "github.com/DependencyTrack/client-go"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &policyResource{}
	_ resource.ResourceWithConfigure   = &policyResource{}
	_ resource.ResourceWithImportState = &policyResource{}
)

func NewPolicyResource() resource.Resource {
	return &policyResource{}
}

type policyResource struct {
	client *dtrack.Client
	semver *Semver
}

type policyResourceModel struct {
	ID        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	Operator  types.String `tfsdk:"operator"`
	Violation types.String `tfsdk:"violation"`
}

func (r *policyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_policy"
}

func (r *policyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Policy.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "UUID for the Policy as generated by DependencyTrack.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the Policy.",
				Required:    true,
			},
			"operator": schema.StringAttribute{
				Description: "Operator to apply to conditions. See DependencyTrack for allowed values.",
				Required:    true,
			},
			"violation": schema.StringAttribute{
				Description: "Violation state for when a condition fails. See DependencyTrack for allowed values.",
				Required:    true,
			},
		},
	}
}

func (r *policyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan policyResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	policyReq := dtrack.Policy{
		Name:           plan.Name.ValueString(),
		Operator:       dtrack.PolicyOperator(plan.Operator.ValueString()),
		ViolationState: dtrack.PolicyViolationState(plan.Violation.ValueString()),
	}
	tflog.Debug(ctx, "Creating a new policy, with name: "+policyReq.Name)
	policyRes, err := r.client.Policy.Create(ctx, policyReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating policy",
			"Error from: "+err.Error(),
		)
		return
	}
	plan = policyResourceModel{
		ID:        types.StringValue(policyRes.UUID.String()),
		Name:      types.StringValue(policyRes.Name),
		Operator:  types.StringValue(string(policyRes.Operator)),
		Violation: types.StringValue(string(policyRes.ViolationState)),
	}

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Created a new policy, with id: "+policyRes.UUID.String())
}

func (r *policyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Fetch state
	var state policyResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Refresh
	tflog.Debug(ctx, "Refreshing policy with id: "+state.ID.ValueString())
	id, diag := TryParseUUID(state.ID, LifecycleRead, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	policy, err := r.client.Policy.Get(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to get updated policy",
			"Error with reading policy: "+id.String()+", from: "+err.Error(),
		)
		return
	}
	state = policyResourceModel{
		ID:        types.StringValue(policy.UUID.String()),
		Name:      types.StringValue(policy.Name),
		Operator:  types.StringValue(string(policy.Operator)),
		Violation: types.StringValue(string(policy.ViolationState)),
	}

	// Update state
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Refreshed policy with id: "+state.ID.ValueString())
}

func (r *policyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get State
	var plan policyResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK
	id, diag := TryParseUUID(plan.ID, LifecycleUpdate, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}
	policyReq := dtrack.Policy{
		UUID:           id,
		Name:           plan.Name.ValueString(),
		Operator:       dtrack.PolicyOperator(plan.Operator.ValueString()),
		ViolationState: dtrack.PolicyViolationState(plan.Violation.ValueString()),
	}
	// Execute
	tflog.Debug(ctx, "Updating policy with id: "+id.String())
	policyRes, err := r.client.Policy.Update(ctx, policyReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to update policy",
			"Error in: "+id.String()+", from: "+err.Error(),
		)
		return
	}

	// Map SDK to TF
	plan = policyResourceModel{
		ID:        types.StringValue(policyRes.UUID.String()),
		Name:      types.StringValue(policyRes.Name),
		Operator:  types.StringValue(string(policyRes.Operator)),
		Violation: types.StringValue(string(policyRes.ViolationState)),
	}

	// Update State
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	tflog.Debug(ctx, "Updated policy with id: "+id.String())
}

func (r *policyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Load state
	var state policyResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Map TF to SDK
	id, diag := TryParseUUID(state.ID, LifecycleDelete, path.Root("id"))
	if diag != nil {
		resp.Diagnostics.Append(diag)
		return
	}

	// Execute
	tflog.Debug(ctx, "Deleting policy with id: "+id.String())
	err := r.client.Policy.Delete(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError(
			"Unable to delete policy",
			"Unexpected error when trying to delete policy: "+id.String()+", from error: "+err.Error(),
		)
		return
	}
	tflog.Debug(ctx, "Deleted policy with id: "+id.String())
}

func (r *policyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func (r *policyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clientInfo, ok := req.ProviderData.(clientInfo)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Configure Type",
			fmt.Sprintf("Expected provider.clientInfo, got %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clientInfo.client
	r.semver = clientInfo.semver
}
