name: CDKTF Bindings

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      cdktf-bindings

permissions:
  contents: write

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Generate bindings
        run: |
          npm install --global cdktf cdktf-cli
          cd cdktf/typescript
          cdktf get
      - name: Get Provider version
        run:
          PROVIDER_VERSION="$(cat .gen/versions.json | jq -r '."registry.terraform.io/solarfactories/dependencytrack"')"
          echo "PROVIDER_VERSION=${PROVIDER_VERSION}" >> "${GITHUB_ENV}"
      - name: Generate package.json
        run: |
          cat package.template.json | jq ".version=\"${PROVIDER_VERSION}\"" > package.json
      - name: Transpile to Javascript
        run: |
          mkdir dist
          npm install
          touch .gen/providers/dependencytrack/tsconfig.json
          tsc --project .gen/providers/dependencytrack --declaration --strict --outDir dist --lib esnext
      - name: Package
        run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: cdktf-typescript
          path: "*.tgz"
          if-no-files-found: "error"
          compression-level: 0
