name: CDKTF Release Typescript GitHub
description: Release Transpiled Typescript Bindings to GitHub Packages

on: workflow_call

inputs:
  javascript-artifact-name:
    description: "Name of the Transpiled Javascript Artifact to download"
    required: true

jobs:
  Release:
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ inputs.javascript-artifact-name }}
      - name: Extract package
        run: |
          FILENAME="$(find . -type f -name 'solarfactories-cdktf-provider-dependencytrack-*.tgz')"
          echo "${FILENAME}"
          tar -xf "${FILENAME}"
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@solarfactories"
      - name: Publish
        run: npm publish
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
