name: CDKTF Bindings

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - cdktf-bindings
      - cdktf-bindings-refactor

permissions:
  contents: write
  packages: write

jobs:
  gen-typescript:
    runs-on: ubuntu-latest
    uses: ./.github/actions/cdktf-gen-typescript.yml
      with:
        typescript-artifact-name: "cdktf-typescript"

  gen-javascript:
    runs-on: ubuntu-latest
    needs:
      - gen-typescript
    uses: ./.github/actions/cdktf-gen-javascript.yml
    with:
      typescript-artifact-name: "cdktf-typescript"
      javascript-artifact-name: "cdktf-javascript"

  rel-typescript-github:
    runs-on: ubuntu-latest
    needs:
      - gen-javascript
    uses: ./.github/actions/cdktf-rel-typescript-github.yml
    with:
      javascript-artifact-name: "cdktf-javascript"

  gen-python:
    runs-on: ubuntu-latest
    # Works locally, but fails without helpful errors in pipeline, so disable for now.
    # If required, may still run `cdktf get` locally within a CDKTF project.
    if: false
    uses: ./.github/actions/cdktf-gen-python.yml
    with:
      python-artifact-name: "cdktf-python"
