name: CFKTF Transpile Javascript Bindings
description: Download an artifact from generated Typescript, transpile to separate Javascript and Type Definition files, and reupload as an artifact

on:
  workflow_call:
    inputs:
      typescript-artifact-name:
        description: "Artifact name of the generated Typescript bindings to download"
        required: true
        type: string
      javascript-artifact-name:
        description: "Artifact name of the generated Javascript bindings to upload"
        required: true
        type: string

jobs:
  Transpile:
    runs-on: ubuntu-latest
    steps:
      - name: Download Typescript Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ inputs.typescript-artifact-name }}
      - name: Extract
        run: tar -xf ${{ inputs.typescript-artifact-name }}.tar.gz
      - name: Transpile to Javascript
        run: |
          mkdir dist
          npm install
          touch tsconfig.json
          tsc --declaration --strict --outDir dist --lib esnext
      - name: Upload Javascript Artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ inputs.javascript-artifact-name }}
            if-no-files-found: "error"
