name: CDKTF Bindings

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      cdktf-bindings

permissions:
  contents: write
  packages: write

jobs:
  gen-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - name: Generate bindings
        working-directory: cdktf/typescript
        run: |
          npm install --global cdktf cdktf-cli
          cdktf get
      - name: Get Provider version
        working-directory: cdktf/typescript
        run: |
          PROVIDER_VERSION="$(cat .gen/versions.json | jq -r '."registry.terraform.io/solarfactories/dependencytrack"')"
          echo "PROVIDER_VERSION=${PROVIDER_VERSION}" >> $GITHUB_ENV
      - name: Generate package.json
        working-directory: cdktf/typescript
        run: |
          cat package.template.json | jq ".version=\"${PROVIDER_VERSION}\"" > package.json
          cat package.json
      - name: Transpile to Javascript
        working-directory: cdktf/typescript
        run: |
          mkdir dist
          npm install
          touch .gen/providers/dependencytrack/tsconfig.json
          tsc --project .gen/providers/dependencytrack --declaration --strict --outDir dist --lib esnext
      - name: Package
        working-directory: cdktf/typescript
        run: npm pack
      - uses: actions/upload-artifact@v4
        with:
          name: cdktf-typescript
          path: "cdktf/typescript/solarfactories-cdktf-provider-dependencytrack-*.tgz"
          if-no-files-found: "error"
          compression-level: 0
  gen-python:
    runs-on: ubuntu-latest
    # Works locally, but fails without helpful errors in pipeline, so disable for now.
    # If required, may still run `cdktf get` locally within a CDKTF project.
    if: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - name: Initialise python venv
        working-directory: cdktf/python
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Generate bindings
        working-directory: cdktf/python
        run: |
          source .venv/bin/activate
          npm install --global cdktf cdktf-cli
          python -m pip install cdktf
          cdktf debug
          cdktf get
      - name: Prepare build directory
        working-directory: cdktf/python
        run: |
          mkdir -p build/src
          cp -r .gen/dependencytrack build/src/solarfactories_cdktf_provider_dependencytrack
          cp LICENCE build
          cp pyproject.toml build
          cp README.md build
      - name: Get Provider version
        working-directory: cdktf/python
        run: |
          PROVIDER_VERSION="$(cat .gen/versions.json | jq -r '."registry.terraform.io/solarfactories/dependencytrack"')"
          echo "PROVIDER_VERSION=${PROVIDER_VERSION}" >> $GITHUB_ENV
      - name: Set Provider version in package
        working-directory: cdktf/python/build
        run: |
          sed -i -e "s/REPLACED_WITH_PROVIDER_VERSION/${PROVIDER_VERSION}/g" pyproject.toml
      - name: Build distributions
        working-directory: cdktf/python/build
        run: |
          source ../.venv/bin/activate
          python -m pip install --upgrade build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: cdktf-python
          path: "cdktf/python/build/dist"
          if-no-files-found: "error"
          compression-level: 0
  rel-typescript-github:
    runs-on: ubuntu-latest
    needs: gen-typescript
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: cdktf-typescript
      - name: Extract package
        run: tar -xf "solarfactories-cdktf-provider-dependencytrack-*.tgz"
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@solarfactories"
      - name: Publish
        run: npm publish
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
